/**
 * @return {string}
 */
// module.exports.Domain = function() {
//   if (process.env.NODE_ENV === 'development') {
//     return 'http://localhost:8008/sc-api'
//   } else {
//     return 'https://api.xluomao.com/supply-chain/api'
//   }
// }

module.exports.ApiURL = {
  auth_login: '/auth/login',
  getInfo: 'GET_LOGIN_AUTHINFO',
  LUCENE_RENEW: '/lucene/renew',
  /*login: '/account/login',
  requistionorder_findpage: '/requistionorder/findpage',
  requistionorder_updateone: '/requistionorder/updateone',
  requistionorder_deleteone: '/requistionorder/deleteoone',
  requistionorder_insertone: '/requistionorder/insertone',
  requistionorder_finddetail: '/requistionorder/finddetail',
  requistionorder_producepdf: '/requistionorder/producepdf',
  requistionorder_couldupdate: '/requistionorder/couldupdate',
  sales_saveone: '/sales/saveone',
  sales_findpage: '/sales/findpage',
  sales_finddetail: '/sales/finddetail',
  settlement_saveone: '/settlement/saveone',
  settlement_findpage: '/settlement/findpage',
  settlement_finddetail: '/settlement/finddetail',
  settlement_delsettlement: '/settlement/delsettlement',
  sales_checkreference: '/sales/checkreference',
  sales_updatesalsorder: '/sales/updatesalsorder',
  sales_delsalesorder: '/sales/delsalesorder',
  sales_importsalesorder: '/sales/importsalesorder',
  purchaseOrderList: '/purchaseOrder/list',
  purchaseOrderDetailList: '/purchaseOrder/detailList',
  purchaseOrderSave: '/purchaseOrder/save',
  invoice_list: '/invoice/list',
  invoice_detail_list: '/invoice/detailList',
  invoice_save: '/invoice/save',
  invoice_update: '/invoice/update',
  invoice_delete: '/invoice/delete',
  database_allcategory: '/database/allcategory',
  database_getproduct: '/database/getproduct',
  database_findproduct: '/database/findproduct',
  database_getallchannel: '/database/getallchannel',
  purchaseOrderUpdate: '/purchaseOrder/update',
  purchaseOrderDelete: '/purchaseOrder/delete',
  loadCanProRefund: '/purchaseOrder/loadCanProRefund',
  sendApproval: '/approval/sendApproval',
  approvalLogList: '/approval/approvalLogList',
  approvalDetailList: '/approval/approvalDetailList',
  abandonApproval: '/approval/abandonApproval',
  doApproval: '/approval/doApproval',
  loadApprovalButtons: '/approval/loadApprovalButtons',
  databaseallcategory: '/database/allcategory',
  databasegetproduct: '/database/getproduct',
  database_unit_list: '/database/unit/list',
  database_unit_update: '/database/unit/update',
  database_getsupplierbyid: '/database/getsupplierbyid',
  database_getallsupplier: '/database/getallsupplier',
  database_getwarehouse: '/database/getwarehouse',
  auth_login: '/account/login',
  auth_getInfo: '/user/info',
  auth_logout: '/account/logout',
  voucher_getAccountList: '/ncdata/getaccount',
  voucher_getAuxiliaryList:'/ncdata/getauxiliary',
  voucher_getCashFlow:'/ncdata/getcashflow',
  voucher_getVoucherList:'/voucher/voucherlist',
  voucher_getVoucherDetail:'/voucher/voucherdetail',
  voucher_addVoucher: '/voucher/savevoucher',
  voucher_beforeAddVoucher: '/voucher/beforesavevoucher',
  voucher_updatevoucher:'/voucher/updatevoucher',
  warehouse_goods_selectAll:'/warehouse/selectAll',
  warehouse_goods_update:'/warehouse/update',
  voucher_beforeCashFlow:'/ncdata/beforeCashFlow',
  storage_purchaseGetList:'/logistics/getList',
  storage_purchaseGetDetail:'/logistics/getDetail',
  storage_purchaseModify:'/purchaseStorage/modify',
  storage_purchaseDelete:'/purchaseStorage/delete',
  storage_purchaseSign:'/purchaseStorage/sign',
  storage_purchaseSave:'/logistics/createcg',
  storage_transfer_list:'/transfer/transferList',
  storage_transfer_detail:'/transfer/transferDetail',
  storage_transfer_create_zk:'/transfer/createzk',
  storage_transfer_get_update_zk:'/transfer/getupdatezkdetail',
  purchase_warehousing_printing:'/printing/purchaseWarehousingPrinting',
  XTC_transGetList:'/storeXTC/getList',
  XTC_transGetDetail:'/storeXTC/getDetailList',
  XTC_saveXTC:'/storeXTC/save',
  XTC_modifyXTC:'/storeXTC/modify',
  XTC_getBOMList:'/storeXTC/getBOMList',
  XTC_getBOMDetailList:'/storeXTC/getBOMDetailList',
  XTC_doSign:'/storeXTC/doSign',
  XTC_getProductOfWarehouse:'/storeXTC/getProductOfWarehouse'*/
}
module.exports.routerMap = {


}
module.exports.Messages = {
  uploadSuccess: '上传成功',
  maxUploadFileNum: '文件数达到上限',
  applySuccess: '申请成功',
  createSuccess: '添加成功',
  editSuccess: '修改成功',
  changeSuccess: '切换成功',
  delSuccess: '删除成功',
  operateSuccess: '操作成功',
  saveSuccess: '保存成功',
  deleteConfirm: '您确定删除?',
  authorizeConfirm: '您确定让帐号失效,重新让用户授权吗?',
  downloadConfirm: '您确定下载吗?',
  bindSuccess: '绑定成功',
  loginNameMandatory: '用户名或手机号不能为空',
  pwdMandatory: '密码不能为空',
  authCodeMandatory: '验证码不能为空',
  logoutConfirm: '您确定退出登录?',
  accountDeleteConfirm: '您确定删除此账号?',
  accountRealNameConfirm: '真实姓名不能为空',
  accountNameMandatory: '账户名不能为空',
  doMainMandatory: '公会域名不能为空',
  roleTypeMandatory: '账户类型不能为空',
  accountNameRegFalse: '账户名只能为英文和数字',
  oldPwdMandatory: '旧密码不能为空',
  newPwdMandatory: '新密码不能为空',
  pwdLengthLessThan: '密码长度不能小于6位',
  pwdNotTheSame: '密码不一致',
  revenuePlatformMandatory: '平台不能为空',
  revenueNameMandatory: '名称不能为空',
  revenueRulesMandatory: '请添加至少一个规则',
  revenueRulesIncorrect: '规则格式不正确',
  revenueTaxIncorrect: '税率格式不正确',
  revenueDeleteConfirm: '您确定删除?',
  generateCodeConfirm: '您确定生成一个邀请码吗?',
  nonePlatformAnchorSaveConfirm: '您还未添加绑定主播,确定要保存吗?',
  revenueRateIncorrect: '分成格式不正确'

}
